---
locale: es
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- value: Resolver una discusión.
  checked: false
- value: Determinar si un cuadro es bello.
  checked: false
- value: Empatizar con otras personas.
  checked: false
- value: Ninguno de los anteriores
  checked: true
name: No está todo programado
