---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- value: ola k ase?
  checked: false
- value: hola, ¿qué haces?
  checked: true
- value: "?hola qué haces¿"
  checked: false
- value: hola, que? haces
  checked: false
- value: hoal, ¿qéu haecs?
  checked: false
name: "¿Qué dices?"
