---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- value: La contabilidad de una empresa.
  checked: true
- value: La reserva de un turno.
  checked: true
- value: Corregir un examen.
  checked: true
- value: La creación de un videojuego.
  checked: true
- value: Realizar videollamadas.
  checked: true
- value: Reconocer imágenes
  checked: true
- value: Conducir un robot en Marte.
  checked: true
name: Vamos programando
