---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- value: "[Bloc de notas](https://es.wikipedia.org/wiki/Bloc_de_notas)"
  checked: false
- value: "[AFIP](https://www.afip.gob.ar/sitio/externos/default.asp)"
  checked: true
- value: "[Instagram](https://www.instagram.com)"
  checked: true
- value: "[Mercado Libre](https://www.mercadolibre.com.ar)"
  checked: true
- value: "[Despegar](https://www.despegar.com.ar)"
  checked: true
- value: "[Buscaminas](https://es.wikipedia.org/wiki/Buscaminas)"
  checked: false
- value: "[Fortnite](https://www.epicgames.com/fortnite/es-ES/home)"
  checked: true
- value: "[Minecraft](https://www.minecraft.net/es-es)"
  checked: true
- value: "[Solitario](https://es.wikipedia.org/wiki/Solitario_Microsoft)"
  checked: false
- value: "[Mumuki](https://mumuki.io/home)"
  checked: true
name: Aplicaciones vs. Sistemas
