---
locale: es
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- value: Una receta de cocina.
  checked: false
- value: Las instrucciones para hacer un origami.
  checked: false
- value: Los pasos para resolver un cubo Rubik.
  checked: false
- value: La lógica que siguen las redes sociales para sugerirte contactos.
  checked: false
- value: Todas las anteriores.
  checked: true
name: Algo con ritmo
