---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- value: "```python\ndef doble(número):\n  return número * 2     \n```\n"
  checked: false
- value: |
    ```python
    def doble(numero):
      return numero + numero
    ```
  checked: false
- value: "```python\ndef doble(numero):\n  return numero * 2     \n```\n"
  checked: true
- value: "```python\ndef doble(numero)\n  return numero * 2     \n```\n"
  checked: false
name: No te comprendo
