---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- value: Licuadora antigua.
  checked: false
- value: Consola de videojuegos.
  checked: true
- value: Navegador GPS.
  checked: true
- value: Teléfono celular.
  checked: true
- value: Una mesa de madera.
  checked: false
- value: Cajero automático.
  checked: true
name: "¿Esto también es una computadora?"
